# Generated by Django 6.0 on 2026-01-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('category', models.CharField()),
                ('type', models.CharField()),
                ('price', models.FloatField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='product/')),
            ],
        ),
    ]
