# Generated by Django 6.0 on 2026-01-26 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientside', '0004_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
