# Generated by Django 6.0 on 2026-01-26 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientside', '0006_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='created_at',
        ),
    ]
