# Generated by Django 6.0 on 2026-01-26 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientside', '0007_remove_order_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='size',
            field=models.CharField(default='M', max_length=10),
        ),
    ]
